language: python

python:
  - "2.7"
  - "3.5"
  - "pypy"
  - "pypy3"

env:
  matrix:
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-django${DJANGO}
  - pip install tox coveralls
  - tox -e $TOX_ENV --notest

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e $TOX_ENV -- pip install coveralls 
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION

matrix:
  fast_finish: true
  include:
    - python: "3.4"
      TOX_ENV=lint
    - python: "3.4"
      env: ENV=docs
      install: pip install tox
      script: tox -e docs
  exclude:
    - python: "3.5"
      env: DJANGO=1.7
    - python: "pypy3"
      env: DJANGO=1.9
